# https://sagiegurari.github.io/cargo-make

[env]

[tasks.check-format]
install_crate = "fmt"
command = "cargo"
args = ["fmt","--","--check"]

[tasks.check-cargo]
install_crate = "cargo-sort"
command = "cargo"
args = ["sort","-c"]

[tasks.bundle]
install_crate = "cargo-bundle"
command = "cargo"
args = ["bundle"]

[tasks.tests]
command = "cargo"
args = ["t"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clippy-nightly]
command = "cargo"
toolchain="nightly"
args = ["clippy"]

[tasks.checks]
dependencies = ["check-cargo","check-format","tests","clippy","clippy-nightly"]
